### List Developers
GET http://localhost:3000/developers

### Get Developer
GET http://localhost:3000/developers/1

### Create Developer
POST http://localhost:3000/developers
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "john.c.calhoun@example.com",
  "dateOfBirth": "1995-05-15"
}

### Update Developer
PATCH http://localhost:3000/developers/dev_qMWn4eRcEWOPTaFk0m6Kx
Content-Type: application/json

{
  "email": "test@example.com"
}

### Delete Developer
DELETE http://localhost:3000/developers/dev_GJeiijJs_pEYcXg87E4y9